services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8545:8545
    environment:
      MNEMONIC: ${MNEMONIC}
      CHAIN_ID: ${CHAIN_ID}
    volumes:
      - ./data/ganache:/db
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' localhost:8545
      interval: 5s
      timeout: 5s
      retries: 5
